### ISSUE TITLE
Adapt Housing Security IPUMS programs for racial equity project

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Equity#1]
Maia - check out some notes on this document: https://urbanorg.app.box.com/notes/74995057046

**Comment by lhendey** [comment]
@mwoluchem  I have some changes for you on #3. I reviewed Equity_data_2010_14.sas.  Please sync because i just changed a few things myself.  Let me know when these are taken care of and then I'll look at the output program. 

- [ ] We are using race alone for the summary tabulations (table B01001B for example).  So i think the "race" variable in iPUMS would be the comparable variable. The ones you are using right now are not mutually exclusive. I need NH white though and not white alone. 

- [ ] Also  please use "[nativity](https://usa.ipums.org/usa-action/variables/NATIVITY#description_section)" instead of citizen to calculate foreign born. 

- [ ] on cost burden - i'd that that to be 30+ (so regular + severe).

**Comment by lhendey** [comment]
@mwoluchem - I met with Peter yesterday and have some ideas for more housing indicators.  And the connection between housing, income and race.  I'll start another issue for the local data. 
From iPUMS: 

- [ ] Thinking about who is vulnerable if we are losing low-cost housing...For units (separately for rental and ownercosts) that are affordable at 30% or less of AMI  - what share are black households? White households?  (We can brainstorm together how to do this.) Between 30-50% of AMI? 50-80% of AMI? This would be looking at based on the rent level and family size - which AMI band does the unit fit into. So if a family of 4 at 30% of AMI =32,100 then then could afford a rent of $802.5 at max (30% of monthly income).  So if a record has 4 people in their family and their rent is less than 802.5 we would flag that as affordable at 30% of AMI - no matter if that family is costburdened. Does that make sense?  

- [ ]Owns a home with a mortgage vs. free and clear by race categories (Also look at elderly and owns free and clear by race categories).

**Comment by mwoluchem** [comment]
Thanks @lhendey ! Quick question on your comment from a few days ago:

- For raceH, I used the hispan variable to calculate because it's not included in race. I think that's correct but just want to make sure those calculations are correct. 
- Unfortunately, nativity isn't offered past 1970. The universe for "[citizen](https://usa.ipums.org/usa-action/variables/CITIZEN#universe_section)" is all foreign-born persons, so I used that to define the variable instead. Doesn't look like there's another proxy that might work as well although if you have any ideas, I'd love to try it out. 
-I changed the geographies to PUMAs. Does this look like how you intend?

On the follow-ups - 

Point 1 (Low-Cost housing) definitely makes sense to me and shouldn't be a problem, I'll find a time on our calendar to meet. 

Point 2 (Mortgage v. Free and Clear) I went ahead and added the vars but I'm not totally sure about how you want those represented. Would you like Mortgage v. Free and Clear the same way cost-burdened and severe cost-burdened households are presented, each in their own table? Just let me know and I can start those. Just committed so you should be able to check out the changes.

**Comment by lhendey** [comment]
@mwoluchem 

- [ ] multiple  race -can we still define? code says: if race in  then raceM=1; 	else raceM=0;

- [ ] see email about foreign born

- [ ] Is ownershpd a created variable? I couldn't find it in the iPUMS doc to evaluate it.  Does it use [mortgage](https://usa.ipums.org/usa-action/variables/MORTGAGE#codes_section)?   Also assignment of zero value for ownmortgage has a different variable name. 

- [ ]  missing are being coded 0 instead of missing for cost burden flags. please check the code for the flags. a frequency of cost_burden indicates that there are 109680 observations less than 30.  Also costburden should be ge 30 which means it should get a flag if 50+ too. They don't seem to be working this way. (so nocostburden should be opposite of costburden ). 

- [ ] shouldn't we be using the hh weight for housing related variables?

- [ ] all=district of columbia not washington region

- [ ] table  1 not running for me?

- [ ] not sure i'm following the output for the employment tables.

Let's discuss these and the Point-1 on low cost housing tomorrow.
