### ISSUE TITLE
Create indicators from realprop data

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/Equity#5]
@mwoluchem - we can talk about this more on monday. a couple of questions I'd want to answer:

1. At the median income for whites - What % of property sales (sf & condo) in 2015 would be affordable? (by census tract).  (For blacks, etc.) Will need to get you code to figure out affordability.  
2. How has assessed value (sf & condo) changed between 2010-2015 in neighborhoods based on their racial composition? (look at both census 2010 and census 2010-14 to figure out classification of neighborhood (tract)-by race something like 75%+ black, 75%+ white, 75%+ latino, or mixed neighborhood.

**Comment by lhendey** [comment]
@mwoluchem - started code in develop-#5 https://github.com/NeighborhoodInfoDC/Equity/commit/c1b765d0d0e3a1bedd9ea347b7ed5bf8102cbf87 for this issue on #1 above.

**Comment by mwoluchem** [comment]
@lhendey 

I was able to complete issue 1 and put through a pull request on this issue but a few questions for clarification: 

1. I used household income as the income measure to determine affordability, instead of family income, since we're using the households and not necessarily the families within the household as the unit of measurement. That's the section with the multiple proc means, intended to get at the correct median income. Was that correct? I can go back and get the family income if you'd rather that measure. 

2. I created the proc summaries in "Work", since I'm not entirely sure if that's the correct sort of output you'd like. Would you mind taking a quick review? They should output to a new dataset but I can push it out with an ODS if they look like what you imagined. 

2a? I couldn't quite figure out how to get the "% Affordable" measures to appear as percentages and not large decimal numbers. Any tips? 

Thanks!

**Comment by lhendey** [comment]
@mwoluchem added in Somala's numbers. I think for the first part of this issue this is about where I want it now. can you do a quick review?

**Comment by lhendey** [comment]
@mwoluchem -
How has assessed value (sf & condo) changed between 2010-2015 in neighborhoods based on their racial composition? (look at both census 2010 and census 2010-14 to figure out classification of neighborhood (tract)-by race something like 75%+ black, 75%+ white, 75%+ latino, or mixed neighborhood.

Pull both census and ACS - use the bridged race categories (so nonhispanic black in this case). 

To get the 2010 assessed value use L:\Libraries\RealProp\Data\proptax_history.sas7bdat. You'll need to select out the 2010 data. 

We're going to use the 2016 assessed value now - so pull that from L:\Libraries\RealProp\Data\ownerpt_2016_04.sas7bdat.  
Merge on ssl.  Limit to single family/condo units.  Get a count of how many properties only have one or the other. . 

summarize to tract (sum=) and then calculate the $ and % change. 

Merge in census/acs race data and run some proc univariates by neighborhood race category on $ and %change.

**Comment by lhendey** [comment]
@katyaabaz - we are working on this issue in the equity repository, on branch develop-#5. if you could pull the property data for @mwoluchem that would be helpful.  See my above comment -  we need the 2010 assessed value and the 2016 assessed value and want to look at the change.

**Comment by katyaabaz** [comment]
@lhendey When merging the data, do you want the count of how many properties are in 2010 but not 2016 and vice versa? I have the program currently producing that count but let me know whether you want me to save it in the Data library or just export into a table.

**Comment by mwoluchem** [comment]
@katyaabaz @lhendey thank you both so much! I'm finally back now, where can I pick this up?

**Comment by lhendey** [comment]
@katyaabaz - can you just do a table in the sas output on the 2010 vs 2016. SOrry -Somehow i don't think this notification came through.

**Comment by lhendey** [comment]
@mwoluchem -
 @katyaabaz has pulled the property data, why don't you start on the race by tract info we need?

**Comment by mwoluchem** [comment]
@lhendey great, thanks!

**Comment by lhendey** [comment]
Issue is closed.
